<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>PitlaneHQ.Desktop</AssemblyName>
    <RootNamespace>PitlaneHQ.Desktop</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>0.8.23</Version>
    <Company>Pitlane HQ</Company>
    <Product>Pitlane HQ Desktop</Product>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2792.45" />
  </ItemGroup>

</Project>
