using System;
using System.ComponentModel;
using MozaPlugin.Devices;
using MozaPlugin.Devices.MBooster;

namespace MozaPlugin.UI
{
    /// <summary>
    /// Row view-model for the mBooster tab's device/pedal list — one row per
    /// connected PEDAL (HID axis), not per physical USB connection: a
    /// standalone mBooster contributes one row (AxisIndex 0), a chained unit
    /// hosting several pedals on one connection contributes one row per
    /// detected axis. This is the single selection mechanism for the tab —
    /// it replaces the old separate trio of "Device combo" + "per-axis Pedal
    /// Roles panel" + "Configure pedal combo", which all overlapped the same
    /// "which pedal, which role, which pedal's config shows below" concerns.
    ///
    /// The label is a plain clickable Button (see
    /// <c>MBoosterDeviceRowButtonStyle</c> in SettingsControl.xaml, "selected"
    /// highlight via a DataTrigger on <see cref="IsSelected"/>); clicking it
    /// selects BOTH the physical device AND this specific pedal for the Pedal
    /// Feel/Sim Input/Effects/Calibration cards below — handled by a plain
    /// Click event (<c>MBoosterDeviceRow_Click</c>) reading this row off the
    /// sender's DataContext, deliberately not a WPF selection/grouping
    /// primitive (RadioButton GroupName + TwoWay binding proved unreliable
    /// when generated by an ItemsControl). <see cref="IsSelected"/> is
    /// therefore plain view state, set only by RefreshMBoosterTab.
    ///
    /// The Role combo writes straight to whichever field
    /// <see cref="MozaMBoosterRegistry.ResolveAxisRole"/> actually reads for
    /// THIS row's (identity, axisIndex) pair — <c>MBoosterDeviceSettings.Role</c>
    /// for a standalone pedal, or <c>AxisRoles[axisIndex]</c> for one pedal of
    /// a chain — so every row's combo is always live (no more disabled state).
    /// Two rows may share a role, as Pit House allows.
    /// </summary>
    internal sealed class MBoosterDeviceRow : INotifyPropertyChanged
    {
        private readonly Action<string, int, MBoosterRole> _onRoleChanged;

        public string Identity { get; }
        public int AxisIndex { get; }

        private string _label;
        /// <summary>Precomputed "{ShortIdentity} (COMn)[ — Pedal N]" text for
        /// the row's Button.</summary>
        public string Label
        {
            get => _label;
            set
            {
                value ??= "";
                if (_label == value) return;
                _label = value;
                Raise(nameof(Label));
            }
        }

        public MBoosterDeviceRow(string identity, int axisIndex, string label, bool isSelected, MBoosterRole role,
            Action<string, int, MBoosterRole> onRoleChanged)
        {
            Identity = identity ?? "";
            AxisIndex = axisIndex;
            _label = label ?? "";
            _isSelected = isSelected;
            _roleIndex = (int)role;
            _onRoleChanged = onRoleChanged ?? throw new ArgumentNullException(nameof(onRoleChanged));
        }

        private bool _isSelected;
        /// <summary>Plain view state — drives the row's DataTrigger highlight
        /// only. Set exclusively by RefreshMBoosterTab (never by the click
        /// handler directly) — see MBoosterDeviceRow_Click in
        /// SettingsControl.xaml.cs.</summary>
        public bool IsSelected
        {
            get => _isSelected;
            set
            {
                if (_isSelected == value) return;
                _isSelected = value;
                Raise(nameof(IsSelected));
            }
        }

        private int _roleIndex;
        // 0=Disabled, 1=Throttle, 2=Brake, 3=Clutch — matches the MBoosterRole
        // enum values AND the ComboBox item order in the DataTemplate, so the
        // selected index maps straight to a role.
        public int RoleIndex
        {
            get => _roleIndex;
            set
            {
                if (_roleIndex == value) return;
                _roleIndex = value;
                Raise(nameof(RoleIndex));
                if (value >= 0 && value <= 3)
                    _onRoleChanged(Identity, AxisIndex, (MBoosterRole)value);
            }
        }

        // ===== Per-pedal calibration routines =====
        // The two hardware routines are addressed per PEDAL, so their buttons
        // live on the pedal's own row rather than once per card: travel
        // calibration carries the role in its cmd id (group 0x26 cmd 12/13/14),
        // and a unit hosting two active pedals answers both on one device id,
        // so a single shared pair of buttons could not say which pedal it
        // meant. Bug GVT5H8B8 is exactly that confusion.
        //
        // All four of these are pushed by SettingsControl.RefreshMBoosterCalUi
        // on every tab tick and on every runner progress event; nothing here
        // decides them.

        private bool _travelCalEnabled;
        public bool TravelCalEnabled
        {
            get => _travelCalEnabled;
            set { if (_travelCalEnabled == value) return; _travelCalEnabled = value; Raise(nameof(TravelCalEnabled)); }
        }

        private bool _motorCalEnabled;
        public bool MotorCalEnabled
        {
            get => _motorCalEnabled;
            set { if (_motorCalEnabled == value) return; _motorCalEnabled = value; Raise(nameof(MotorCalEnabled)); }
        }

        private string _travelCalLabel = "";
        /// <summary>Button caption — the routine's name, or Stop while it runs.</summary>
        public string TravelCalLabel
        {
            get => _travelCalLabel;
            set { value ??= ""; if (_travelCalLabel == value) return; _travelCalLabel = value; Raise(nameof(TravelCalLabel)); }
        }

        private string _motorCalLabel = "";
        public string MotorCalLabel
        {
            get => _motorCalLabel;
            set { value ??= ""; if (_motorCalLabel == value) return; _motorCalLabel = value; Raise(nameof(MotorCalLabel)); }
        }

        private string _calStatus = "";
        /// <summary>Progress/result line for a run on THIS pedal. Empty hides
        /// the row's status line (see the EmptyStringToVisibility converter on
        /// it in the DataTemplate), so an idle list costs no extra height.</summary>
        public string CalStatus
        {
            get => _calStatus;
            set { value ??= ""; if (_calStatus == value) return; _calStatus = value; Raise(nameof(CalStatus)); }
        }

        /// <summary>True when the calibration buttons should exist at all for
        /// this pedal — a passive pedal has no motor to sweep or locate.</summary>
        private bool _calVisible;
        public bool CalVisible
        {
            get => _calVisible;
            set { if (_calVisible == value) return; _calVisible = value; Raise(nameof(CalVisible)); }
        }

        public event PropertyChangedEventHandler? PropertyChanged;
        private void Raise(string name) => PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(name));
    }
}
